fragment TextImageBlockFragment on ComponentContentBlocksTextImageBlock {
  title
  content
  images {
    data {
      attributes {
        name
        width
        height
        url
        alternativeText
        caption
        formats
      }
    }
  }
  ctaButton {
    label
    link
    variant
  }
  blockProperties {
    variant
    orientation
    slug
  }
}
