mutation CreateActivity(
  $name: String!
  $startdate: Date!
  $enddate: Date!
  $starttime: Time!
  $endtime: Time!
  $description: String!
  $group: ID!
) {
  createActivity(
    data: {
      title: $name
      description: $description
      startDate: $startdate
      startTime: $starttime
      endDate: $enddate
      endTime: $endtime
      group: $group
    }
  ) {
    data {
      id
    }
  }
}