query getUserInfo($UID: ID){
  leaders(filters: {user: {id: {eq:$UID}}}) {
    data {
      attributes {
        group {
          data {
            attributes {
              slug
            }
          }
        }
      }
    }
  }
}