fragment ActivityBlockFragment on ComponentContentBlocksActivitiesBlock {
  title
  initialItems
  blockProperties {
    variant
    orientation
    slug
  }
  cta: callToAction {
    variant
    orientation
    slug
  }
}
