fragment FAQBlockFragment on ComponentContentBlocksFaqBlock {
  title
  bottomText
  faqItems {
    data {
      attributes {
        question
        answer
        image {
          data {
            attributes {
              name
              width
              height
              url
              alternativeText
              caption
              formats
              blurhash
            }
          }
        }
        callToAction {
          label
          link
          variant
        }
      }
    }
  }
  blockProperties {
    variant
    orientation
    slug
  }
}
