fragment FormFragment on ComponentContentBlocksForm {
  redirect
  action
  formVariant: variant
  formOrientation: orientation
  formSmallPadding: modSmallPadding
  formMargin: modMargin
  inputs {
    label
    type
    uid
    required
    options
  }
}
