fragment GalleryBlockFragment on ComponentContentBlocksGalleryBlock {
  title
  initialItems
  images {
    data {
      attributes {
        ...ImageFragment
      }
    }
  }
  cta: callToAction {
    title
    intro
    ctaLabel
    ctaLink
  }
  blockProperties {
    variant
    orientation
    slug
  }
}
