fragment GroupsBlockFragment on ComponentContentBlocksGroupsBlock {
  title
  groups {
    data {
      attributes {
        name
        slug
        logo {
          data {
            attributes {
              ...ImageFragment
            }
          }
        }
      }
    }
  }
  blockProperties {
    variant
    orientation
    slug
  }
  cta: callToAction {
    title
    intro
    ctaLabel
    ctaLink
  }
}
