fragment HeroBlockFragment on ComponentContentBlocksHeroBlock {
  title
  subtitle
  variant
  callToAction {
    label
    link
    variant
  }
  socialsCta {
    title
    socialItems {
      data {
        attributes {
          title
          link
          icon
        }
      }
    }
  }
  yearTheme {
    data {
      attributes {
        title
        image {
          data {
            attributes {
              ...ImageFragment
            }
          }
        }
      }
    }
  }
  bgImage {
    data {
      attributes {
        ...ImageFragment
      }
    }
  }
}
