fragment PageMetaFragment on ComponentGeneralPageMeta {
  pageTitle
  pageDescription
  noIndex
  slug
  metaImage {
    data {
      attributes {
        ...ImageFragment
      }
    }
  }
  metaSocial {
    socialNetwork
    title
    description
    image {
      data {
        attributes {
          ...ImageFragment
        }
      }
    }
  }
}
