fragment TextImageBlockFragment on ComponentContentBlocksTextImageBlock {
  title
  content
  orientation: variant
  images {
    data {
      attributes {
        ...ImageFragment
      }
    }
  }
  ctaButton {
    label
    link
    variant
  }
  blockProperties {
    variant
    orientation
    slug
  }
}
