fragment YearThemeBlockFragment on ComponentContentBlocksYearThemeBlock {
  title
  blockProperties {
    variant
    orientation
    slug
  }
  cta: callToAction {
    title
    intro
    ctaLabel
    ctaLink
  }
}
