mutation (
  $firstName: String
  $lastName: String
  $street: String
  $houseNumber: String
  $busNumber: String
  $arealCode: String
  $city: String
  $phoneNumber: String
  $email: String
  $sex: ENUM_MEMBER_GENDER
  $birthDate: Date
  $akabe: Boolean
) {
  createMember(
    data: {
      firstName: $firstName
      lastName: $lastName
      birthday: $birthDate
      street: $street
      number: $houseNumber
      bus: $busNumber
      postCode: $arealCode
      city: $city
      phone: $phoneNumber
      email: $email
      akabe: $akabe
      gender: $sex
    }
  ) {
    data {
      id
    }
  }
}
