name: Deploy to Netlify on Release

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SITE_URL: ${{ secrets.SITE_URL }}
      APP_ENV: production
      NEXT_PUBLIC_APP_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_APP_BACKEND_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Install dependencies
        run: npm install

      - name: Link to Netlify Site
        run: netlify link --id ${{ secrets.NETLIFY_SITE_ID }}
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Build project with netlify
        run: netlify build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Deploy to Netlify
        run: netlify deploy --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
