name: Deploy to Netlify on Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_ENV: production
      SITE_URL: ${{ secrets.SITE_URL }}
      NEXT_PUBLIC_APP_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_APP_BACKEND_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Install Netlify CLI and Plugins
        run: npm install netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify build && netlify deploy --prod
